"""
config.py — the engine's config loader. DO NOT EDIT THIS FILE.
================================================================================
Edit your settings in personal/userconfig.py instead. This file is machinery:

  1. imports your personal values from personal/userconfig.py,
  2. defines the file paths every tool reads/writes (all under personal/),
  3. exposes terms_to_regex(), which compiles your plain-word lists into rules.

Every tool does `import config` and gets both your values and the paths, so the
split is invisible to them. Keeping the machinery here (tracked, shareable) and
the values in personal/userconfig.py (gitignored) means the system can be updated
with `git pull` without ever touching — or exposing — your personal settings.
"""

import os
import re
import sys

# --- locate and load the user's personal values -----------------------------
_REPO = os.path.dirname(os.path.abspath(__file__))
_PERSONAL = os.path.join(_REPO, "personal")
sys.path.insert(0, _PERSONAL)
try:
    from userconfig import *  # noqa: F403 — the user's personal values
except ImportError as _e:
    raise SystemExit(
        "config.py: could not import personal/userconfig.py.\n"
        "First-time setup: copy starter/userconfig.template.py to "
        "personal/userconfig.py and fill in your details.\n"
        f"(underlying error: {_e})"
    ) from None

# =============================================================================
# FILE PATHS  (all personal data lives under personal/, gitignored; the dashboard
# shell is the one shared, PII-free asset and lives in engine/)
# =============================================================================
DATA_DIR = os.path.join(_PERSONAL, "data")
PIPELINE_MD = os.path.join(DATA_DIR, "pipeline.md")
JOBS_JSON = os.path.join(DATA_DIR, "jobs.json")
LEADS_MD = os.path.join(DATA_DIR, "leads.md")
LEADS_RAW = os.path.join(DATA_DIR, "leads_raw.csv")
LEADS_SCORED = os.path.join(DATA_DIR, "leads_scored.csv")
LEADS_ATS = os.path.join(DATA_DIR, "leads_ats.csv")
SWEEP_STATE = os.path.join(DATA_DIR, "sweep_state.json")
PROFILE_MD = os.path.join(_PERSONAL, "career-profile.md")
APPLICATIONS_DIR = os.path.join(_PERSONAL, "applications")


# ---- helper: turns the plain words in userconfig into matching rules. --------
def terms_to_regex(terms):
    """['data governance', 'ai coe'] -> compiled word-boundary regex, case-insensitive.

    A space in your term matches any run of spaces/hyphens/dashes, so the term
    "enablement shared services" correctly matches a real title written
    "Enablement - Shared Services". (Modern re.escape() leaves spaces alone, so we
    substitute the plain space, not an escaped one - that bug silently broke every
    multi-word term until a regression test caught it.)
    """
    if not terms:
        return re.compile(r"(?!x)x")  # matches nothing
    parts = []
    for t in terms:
        t = t.strip()
        if not t:
            continue
        p = re.escape(t)
        p = p.replace("\\ ", r"[\s\-–—]+")  # older Pythons escape the space
        p = p.replace(" ", r"[\s\-–—]+")  # modern Pythons do not
        parts.append(p)
    return re.compile(r"\b(" + "|".join(parts) + r")\b", re.I)
