#!/usr/bin/env python3
"""
backup_personal.py — package the irreplaceable half of personal/ into a dated,
restorable archive, and put it somewhere that is not this disk.

    python engine/backup_personal.py                 # back up the core, prune old
    python engine/backup_personal.py --full          # include generated .docx/.pdf
    python engine/backup_personal.py --dry-run       # list what would go in
    python engine/backup_personal.py --list          # what is already backed up
    python engine/backup_personal.py --verify        # re-extract the newest, check hashes
    python engine/backup_personal.py --restore <zip> --into <dir>

WHY THIS EXISTS. `personal/` is gitignored, which protects it from being published
and protects it from nothing else. Every commit in this repo is replicated to
GitHub; the profile, the board, and the accumulated judgment in them exist on one
disk. The gitignore is the reason a backup is needed, not a substitute for one.

WHY A DATED ARCHIVE RATHER THAN SYNCING THE FOLDER. Sync is not backup. If a script
truncates jobs.json, OneDrive replicates the truncation faithfully and within
seconds, and the good copy is gone from both ends. Dated archives are the cheapest
thing that survives a bad write, because yesterday's file is a separate object that
nothing is propagating into.

WHAT COUNTS AS CORE. Most of personal/ by bytes is generated documents, and every
one of them rebuilds from a .json spec that is a fraction of its size. So the
default captures SOURCES: the hand-authored markdown, userconfig.py, the board, the
metric registry, and the application specs. `--full` adds the rendered .docx/.pdf,
which is worth running occasionally because a submitted document is a record of
what was actually sent, not just what could be regenerated.

The exclusion list is a DENYLIST on purpose. An allowlist silently drops any new
kind of file someone adds later, and silence is the failure mode a backup cannot
have. Anything unrecognised is included.

BUILD VS ADOPT. restic is the better general answer and is what to reach for if
encryption at rest or real snapshot history matters. It loses here because it backs
up bytes without meaning: it cannot know that .docx are derived, and its restore
gives you files rather than a checked-out tree you can verify. This is ~200 lines
because the value is in knowing which files matter and proving a restore works, not
in moving them.
"""

import argparse
import datetime as _dt
import hashlib
import json
import os
import shutil
import sys
import tempfile
import zipfile
from typing import Any

# Generated by build_application.py from the .json specs beside them.
DERIVED_SUFFIXES = {".docx", ".pdf", ".pyc", ".pyo"}
# Overwritten wholesale by the next sweep; keeping them costs megabytes and buys nothing.
DERIVED_NAMES = {"leads_raw.csv", "leads_scored.csv", "leads_ats.csv"}
SKIP_DIRS = {"__pycache__", ".ipynb_checkpoints"}

# If any of these is missing from an archive, the archive is not a restore point
# regardless of how many files it has. Checked on write AND on verify.
REQUIRED = (
    "personal/career-profile.md",
    "personal/userconfig.py",
    "personal/data/jobs.json",
)

MANIFEST = "MANIFEST.json"
FORMAT_VERSION = 1


def sha256(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def is_derived(name: str) -> bool:
    return os.path.splitext(name)[1].lower() in DERIVED_SUFFIXES or name in DERIVED_NAMES


def collect(personal_dir: str, full: bool = False) -> tuple[list[str], list[str]]:
    """(included, excluded) as repo-relative posix paths, sorted.

    Both lists are returned because a backup that quietly drops things is worse
    than one that drops nothing: the caller prints the exclusions so a human can
    notice the day something important starts matching the denylist.
    """
    root = os.path.dirname(os.path.abspath(personal_dir))
    inc: list[str] = []
    exc: list[str] = []
    for dirpath, dirnames, filenames in os.walk(personal_dir):
        dirnames[:] = sorted(d for d in dirnames if d not in SKIP_DIRS)
        for name in sorted(filenames):
            abs_p = os.path.join(dirpath, name)
            rel = os.path.relpath(abs_p, root).replace("\\", "/")
            (exc if (not full and is_derived(name)) else inc).append(rel)
    return inc, exc


def _restore_doc(mode: str, missing: list[str]) -> str:
    lines = [
        "# Restoring this archive",
        "",
        f"Mode: **{mode}**. Written by `engine/backup_personal.py`.",
        "",
        "Paths inside are repo-relative, so a restore is an extract into the repo root:",
        "",
        "```bash",
        "python engine/backup_personal.py --restore <this-file>.zip --into /path/to/job-applications",
        "```",
        "",
        "Or by hand: unzip into the repo root so `personal/` lands beside `engine/`.",
        "Delete MANIFEST.json and RESTORE.md afterwards; they are archive metadata, not repo files.",
        "",
        "## After restoring",
        "",
        "```bash",
        "python tools/ci_local.py                                   # the engine still runs",
        "python engine/repair_pipeline.py                           # board integrity",
        "python engine/build_application.py personal/applications/<name>   # rebuild documents",
        "```",
    ]
    if mode == "core":
        lines += [
            "",
            "## What is not in here",
            "",
            "Rendered .docx and .pdf are excluded by default; rebuild them from the .json",
            "specs with the command above. Sweep caches (leads_raw/scored/ats.csv) are",
            "excluded too and refill on the next sweep.",
        ]
    if missing:
        lines += [
            "",
            "## WARNING",
            "",
            "This archive was written with these required files ABSENT:",
            "",
        ]
        lines += [f"- `{m}`" for m in missing]
    return "\n".join(lines) + "\n"


def create(
    personal_dir: str,
    dest_dir: str,
    full: bool = False,
    today: _dt.date | None = None,
    repo_name: str = "job-applications",
) -> tuple[str, dict[str, Any]]:
    """Write one dated archive. Returns (path, manifest)."""
    inc, exc = collect(personal_dir, full=full)
    root = os.path.dirname(os.path.abspath(personal_dir))
    mode = "full" if full else "core"
    stamp = (today or _dt.date.today()).isoformat()

    path = os.path.join(dest_dir, f"bellows-personal-{mode}-{stamp}.zip")
    files: list[dict[str, Any]] = []
    total = 0
    os.makedirs(dest_dir, exist_ok=True)

    tmp = path + ".partial"
    with zipfile.ZipFile(tmp, "w", zipfile.ZIP_DEFLATED) as zf:
        for rel in inc:
            abs_p = os.path.join(root, rel)
            size = os.path.getsize(abs_p)
            files.append({"path": rel, "sha256": sha256(abs_p), "bytes": size})
            total += size
            zf.write(abs_p, rel)
        present = {f["path"] for f in files}
        missing = [r for r in REQUIRED if r not in present]
        manifest = {
            "format_version": FORMAT_VERSION,
            "created": _dt.datetime.now().replace(microsecond=0).isoformat(),
            "mode": mode,
            "repo": repo_name,
            "file_count": len(files),
            "total_bytes": total,
            "excluded_count": len(exc),
            "missing_required": missing,
            "files": files,
        }
        zf.writestr(MANIFEST, json.dumps(manifest, indent=1) + "\n")
        zf.writestr("RESTORE.md", _restore_doc(mode, missing))

    # Rename last so an interrupted run never leaves a plausible-looking archive.
    os.replace(tmp, path)
    return path, manifest


def read_manifest(zip_path: str) -> dict[str, Any]:
    with zipfile.ZipFile(zip_path) as zf:
        return json.loads(zf.read(MANIFEST).decode("utf-8"))


def verify(zip_path: str) -> dict[str, Any]:
    """Extract to a temp dir and re-hash every file. Returns a report dict.

    Deliberately does a real extraction rather than reading hashes back out of the
    same manifest it wrote. A checksum compared against itself proves nothing; this
    proves the bytes survived the round trip.
    """
    report: dict[str, Any] = {
        "zip": zip_path,
        "checked": 0,
        "mismatched": [],
        "missing": [],
        "missing_required": [],
    }
    man = read_manifest(zip_path)
    report["manifest"] = man
    with tempfile.TemporaryDirectory() as tmp:
        with zipfile.ZipFile(zip_path) as zf:
            for entry in zf.infolist():
                if _unsafe(entry.filename):
                    report["mismatched"].append(f"{entry.filename} (unsafe path)")
                    continue
                zf.extract(entry, tmp)
        for f in man["files"]:
            out = os.path.join(tmp, f["path"].replace("/", os.sep))
            if not os.path.isfile(out):
                report["missing"].append(f["path"])
                continue
            report["checked"] += 1
            if sha256(out) != f["sha256"]:
                report["mismatched"].append(f["path"])
        present = {f["path"] for f in man["files"]}
        report["missing_required"] = [r for r in REQUIRED if r not in present]
    report["ok"] = not (report["mismatched"] or report["missing"] or report["missing_required"])
    return report


def _unsafe(name: str) -> bool:
    """A zip member that would escape the extraction root."""
    n = name.replace("\\", "/")
    return n.startswith("/") or ".." in n.split("/") or (len(n) > 1 and n[1] == ":")


def restore(zip_path: str, into: str, force: bool = False) -> tuple[list[str], list[str]]:
    """Extract into a repo root. Refuses to clobber by default. Returns (written, skipped)."""
    written: list[str] = []
    skipped: list[str] = []
    with zipfile.ZipFile(zip_path) as zf:
        for entry in zf.infolist():
            if entry.is_dir() or entry.filename in (MANIFEST, "RESTORE.md"):
                continue
            if _unsafe(entry.filename):
                skipped.append(f"{entry.filename} (unsafe path)")
                continue
            target = os.path.join(into, entry.filename.replace("/", os.sep))
            if os.path.exists(target) and not force:
                skipped.append(entry.filename)
                continue
            os.makedirs(os.path.dirname(target), exist_ok=True)
            with zf.open(entry) as src, open(target, "wb") as dst:
                shutil.copyfileobj(src, dst)
            written.append(entry.filename)
    return written, skipped


def existing(dest_dir: str) -> list[str]:
    if not os.path.isdir(dest_dir):
        return []
    got = [
        os.path.join(dest_dir, f)
        for f in os.listdir(dest_dir)
        if f.startswith("bellows-personal-") and f.endswith(".zip")
    ]
    return sorted(got, key=lambda p: (os.path.getmtime(p), p))


def prune(dest_dir: str, keep: int) -> list[str]:
    """Delete all but the newest `keep` archives. Never empties the directory."""
    got = existing(dest_dir)
    if keep <= 0 or len(got) <= keep:
        return []
    doomed = got[: len(got) - keep]
    for p in doomed:
        os.remove(p)
    return doomed


# ------------------------------------------------------- is the destination real?
#
# A folder named OneDrive is not OneDrive. Windows creates that folder during setup
# whether or not anyone ever signs in, so writing to it succeeds, reports success,
# and uploads nothing. That is worse than having no backup, because no backup at
# least tells you the truth. The checks below establish whether a sync client is
# actually LINKED, not whether a directory with a promising name exists.


def _windows() -> bool:
    return os.name == "nt"


def _onedrive_roots() -> list[tuple[str, bool, str]]:
    """(path, live, why) for each configured OneDrive folder."""
    if not _windows():
        return []
    try:
        import winreg
    except ImportError:  # pragma: no cover - Windows-only import
        return []
    out: list[tuple[str, bool, str]] = []
    try:
        with winreg.OpenKey(winreg.HKEY_CURRENT_USER, r"SOFTWARE\Microsoft\OneDrive\Accounts") as k:
            i = 0
            while True:
                try:
                    sub = winreg.EnumKey(k, i)
                except OSError:
                    break
                i += 1
                try:
                    with winreg.OpenKey(k, sub) as a:
                        folder, _ = winreg.QueryValueEx(a, "UserFolder")
                    if folder:
                        out.append((folder, True, f"OneDrive account {sub} is linked"))
                except OSError:
                    continue
    except OSError:
        pass
    if not out:
        home = os.path.join(os.path.expanduser("~"), "OneDrive")
        if os.path.isdir(home):
            out.append((home, False, "the OneDrive folder exists but NO ACCOUNT IS LINKED"))
    return out


def _gdrive_roots() -> list[tuple[str, bool, str]]:
    if not _windows():
        return []
    installed = os.path.isdir(os.path.join(os.environ.get("LOCALAPPDATA", ""), "Google", "DriveFS"))
    out: list[tuple[str, bool, str]] = []
    for letter in "GHIJKLMNOPQRSTUVWXYZ":
        mount = f"{letter}:\\My Drive"
        if os.path.isdir(mount):
            out.append((mount, True, f"Google Drive mounted at {letter}:"))
    home = os.path.join(os.path.expanduser("~"), "Google Drive")
    if os.path.isdir(home):
        out.append(
            (
                home,
                installed,
                "Google Drive folder" + ("" if installed else ", client NOT installed"),
            )
        )
    return out


def _dropbox_roots() -> list[tuple[str, bool, str]]:
    if not _windows():
        return []
    info = os.path.join(os.environ.get("LOCALAPPDATA", ""), "Dropbox", "info.json")
    if not os.path.isfile(info):
        return []
    try:
        with open(info, encoding="utf-8") as fh:
            data = json.load(fh)
    except (OSError, ValueError):
        return []
    return [(v["path"], True, "Dropbox is linked") for v in data.values() if v.get("path")]


def cloud_roots() -> list[tuple[str, bool, str]]:
    return _onedrive_roots() + _gdrive_roots() + _dropbox_roots()


def _under(child: str, parent: str) -> bool:
    c, p = os.path.abspath(child).rstrip("\\/"), os.path.abspath(parent).rstrip("\\/")
    return c.lower() == p.lower() or c.lower().startswith(p.lower() + os.sep)


def destination_status(
    dest: str, roots: list[tuple[str, bool, str]] | None = None
) -> tuple[str, str]:
    """('synced' | 'unlinked' | 'local', explanation).

    'unlinked' is the dangerous one and the reason this function exists: the path
    looks like cloud storage, so everything reads as fine, and nothing leaves the
    machine. It is called out separately from an ordinary local folder because a
    deliberate local target is a choice, and this is a trap.
    """
    for path, live, why in cloud_roots() if roots is None else roots:
        if _under(dest, path):
            return ("synced" if live else "unlinked"), why
    return "local", "not inside any linked cloud-sync folder on this machine"


# --------------------------------------------------------------------------- CLI


def _dest_from_config(cfg: Any) -> tuple[str | None, str | None]:
    """BACKUP_DIR from userconfig, else a discovered cloud root, else None.

    Discovery proposes only LINKED roots. Matching on a folder name would hand back
    the same trap destination_status() exists to catch - an unsigned-in OneDrive
    directory is present on a huge number of Windows machines, and proposing it as
    the default would be this tool recommending its own worst failure mode.
    """
    d = getattr(cfg, "BACKUP_DIR", None)
    if d:
        return os.path.expandvars(os.path.expanduser(d)), "userconfig.py"
    for path, live, why in cloud_roots():
        if live:
            return os.path.join(path, "Bellows Backups"), f"discovered ({why})"
    return None, None


def _human(n: float) -> str:
    for unit in ("B", "KB", "MB"):
        if n < 1024:
            return f"{n:.0f} B" if unit == "B" else f"{n:.1f} {unit}"
        n /= 1024
    return f"{n:.1f} GB"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Back up the core of personal/ to a dated archive.")
    ap.add_argument("--full", action="store_true", help="include generated .docx/.pdf")
    ap.add_argument("--dry-run", action="store_true", help="list what would be included")
    ap.add_argument("--list", action="store_true", dest="do_list", help="list existing archives")
    ap.add_argument(
        "--verify", nargs="?", const="", metavar="ZIP", help="verify an archive (default: newest)"
    )
    ap.add_argument("--restore", metavar="ZIP", help="restore an archive")
    ap.add_argument("--into", metavar="DIR", help="restore target (repo root)")
    ap.add_argument(
        "--force", action="store_true", help="allow --restore to overwrite existing files"
    )
    ap.add_argument("--dest", metavar="DIR", help="override the backup destination")
    ap.add_argument("--keep", type=int, default=14, help="archives to retain (default 14)")
    ap.add_argument(
        "--allow-local",
        action="store_true",
        help="accept a destination that no sync client is uploading (e.g. a second physical disk)",
    )
    ap.add_argument("--where", action="store_true", help="show cloud folders found on this machine")
    a = ap.parse_args(argv)

    import _paths  # noqa: F401
    import config as CFG

    repo = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    personal = os.path.join(repo, "personal")

    if a.restore:
        if not a.into:
            print("  --restore needs --into <repo root>")
            return 2
        written, skipped = restore(a.restore, a.into, force=a.force)
        print(f"  restored {len(written)} file(s) into {a.into}")
        if skipped:
            print(f"  skipped {len(skipped)} that already existed (use --force to overwrite):")
            for s in skipped[:10]:
                print(f"    {s}")
        return 0

    if a.where:
        roots = cloud_roots()
        if not roots:
            print("  No cloud-sync client is linked on this machine.")
            print("  Install and sign in to OneDrive, Google Drive, or Dropbox, then set")
            print("  BACKUP_DIR in personal/userconfig.py to a folder inside it.")
            return 1
        print("  Cloud folders on this machine:\n")
        for path, live, why in roots:
            print(f"    {'LIVE  ' if live else 'DEAD  '} {path}\n            {why}")
        # Non-zero when nothing is actually uploading, even though folders were
        # found: "I listed something" must not read as "you are covered".
        if not any(live for _, live, _ in roots):
            print("\n  None of these are syncing. Nothing here leaves the machine.")
            return 1
        return 0

    dest: str | None = a.dest
    source: str | None = "--dest"
    if not dest:
        dest, source = _dest_from_config(CFG)
    if not dest:
        print("  No backup destination. Add to personal/userconfig.py:\n")
        print('      BACKUP_DIR = r"C:\\Users\\you\\OneDrive\\Bellows Backups"\n')
        print("  or pass --dest. No cloud folder was found under your home directory.")
        return 2

    # The archive is 100% PII. Inside the repo it is one `git add -f` or one
    # gitignore edit away from being published, so this is refused outright.
    if os.path.abspath(dest).startswith(os.path.abspath(repo) + os.sep):
        print(f"  REFUSED: destination is inside the repo.\n    {dest}")
        print("  This archive is entirely PII. Put it somewhere the repo cannot reach.")
        return 2

    # Checked before writing, so the warning is not buried under a success report.
    state, why = destination_status(dest)
    if state != "synced" and not a.allow_local:
        label = "IS NOT SYNCING" if state == "unlinked" else "IS LOCAL ONLY"
        print(f"  ⚠ THE DESTINATION {label}\n    {dest}")
        print(f"    {why}\n")
        if state == "unlinked":
            print("  A folder named after a cloud service is not that cloud service. Writing")
            print("  here succeeds and uploads nothing, which is worse than no backup because")
            print("  no backup does not claim to be one.\n")
        print("  Fix it one of these ways:")
        print("    - sign in to the sync client, then re-run")
        print("    - `--where` to see what IS linked here")
        print("    - `--allow-local` if a second physical disk is what you meant")
        print("      (protects against a disk failure, not against losing the machine)")
        return 3

    if a.do_list:
        got = existing(dest)
        print(f"  {len(got)} archive(s) in {dest}\n")
        for p in reversed(got):
            try:
                m = read_manifest(p)
                flag = "  ⚠ INCOMPLETE" if m.get("missing_required") else ""
                print(
                    f"    {os.path.basename(p):<44} {m['mode']:<5} {m['file_count']:>4} files"
                    f"  {_human(os.path.getsize(p)):>9}{flag}"
                )
            except Exception as e:
                print(f"    {os.path.basename(p):<44} UNREADABLE ({type(e).__name__})")
        return 0

    if a.verify is not None:
        found = existing(dest)
        target = a.verify or (found[-1] if found else "")
        if not target:
            print(f"  nothing to verify in {dest}")
            return 2
        r = verify(target)
        print(f"  {os.path.basename(target)}")
        print(
            f"    mode {r['manifest']['mode']}, {r['checked']} file(s) re-hashed after extraction"
        )
        for label, key in (
            ("mismatched", "mismatched"),
            ("missing", "missing"),
            ("missing required", "missing_required"),
        ):
            if r[key]:
                print(f"    {label}: {len(r[key])}")
                for x in r[key][:10]:
                    print(f"      {x}")
        print("    VERIFIED" if r["ok"] else "    FAILED")
        return 0 if r["ok"] else 1

    inc, exc = collect(personal, full=a.full)
    if a.dry_run:
        total = sum(os.path.getsize(os.path.join(repo, p)) for p in inc)
        print(f"  would include {len(inc)} file(s), {_human(total)}")
        print(f"  would exclude {len(exc)} generated/regenerable file(s)")
        print(f"  destination: {dest}  ({source})\n")
        for p in inc[:25]:
            print(f"    {p}")
        if len(inc) > 25:
            print(f"    ... and {len(inc) - 25} more")
        return 0

    path, man = create(personal, dest, full=a.full, repo_name=os.path.basename(repo))
    print(f"  wrote {os.path.basename(path)}")
    print(
        f"    {man['file_count']} file(s), {_human(man['total_bytes'])} uncompressed"
        f" -> {_human(os.path.getsize(path))} on disk"
    )
    print(f"    excluded {man['excluded_count']} generated/regenerable file(s)")
    print(f"    {dest}  ({source})")
    if man["missing_required"]:
        print("    ⚠ REQUIRED FILES ABSENT: " + ", ".join(man["missing_required"]))

    r = verify(path)
    print(
        f"    verified: {r['checked']} file(s) re-hashed after extraction"
        + ("" if r["ok"] else "  ** FAILED **")
    )
    dropped = prune(dest, a.keep)
    if dropped:
        print(f"    pruned {len(dropped)} archive(s) beyond --keep {a.keep}")
    return 0 if r["ok"] else 1


if __name__ == "__main__":
    sys.exit(main())
