#!/usr/bin/env python3
"""
docx_finalize.py — normalize a generated .docx's metadata, HONESTLY.

python-docx leaves misleading fingerprints: it names "python-docx" as the author
(it isn't — you are), advertises "generated by python-docx" in the description,
and inherits a stale 2013 timestamp and an Application value from its Word-authored
template. This corrects those to the truth:

  - author / lastModifiedBy  -> you (you authored the content; the tool only rendered it)
  - description / Company     -> blank (drop the generator advert)
  - created / modified        -> now (the file WAS created just now)
  - revision                  -> 1 (it's the first save)
  - Application               -> blank (assert nothing; don't claim it was made in Word)

DELIBERATE NON-GOALS (the honesty rule applies to metadata too): it does NOT
backdate the file to fake an older creation date, does NOT inflate the revision
count to fake an edit history, and does NOT claim the document was written or
edited in an app it wasn't. The creation time reads as "now" because that's when
you generated it — that's the honest value, not a tell to disguise.

USAGE
  python docx_finalize.py "in.docx" "Firstname Lastname - Resume.docx" --author "Firstname Lastname"
  # or import finalize(in_path, out_path, author=...) from a generation script.

It only touches METADATA, never the resume content.
"""

import argparse
import io
import re
import sys
import zipfile
from datetime import datetime, timezone

import _paths  # noqa: F401  (side-effect: adds repo root to sys.path for `import config`)
import config  # for the default author (from personal/userconfig.py)


def finalize(in_path, out_path, author=None):
    author = author or config.LEGAL_NAME
    now = datetime.now(timezone.utc).replace(microsecond=0)
    created = modified = now  # the file is created + saved right now
    revision = 1  # first save — no faked edit history

    def ts(d):
        return d.strftime("%Y-%m-%dT%H:%M:%SZ")

    zin = zipfile.ZipFile(in_path, "r")
    buf = io.BytesIO()
    zout = zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED)

    for item in zin.infolist():
        data = zin.read(item.filename)

        if item.filename == "docProps/core.xml":
            x = data.decode("utf-8", "ignore")
            x = re.sub(
                r"<dc:creator>.*?</dc:creator>", f"<dc:creator>{author}</dc:creator>", x, flags=re.S
            )
            # description often carries "generated by python-docx" -> blank it
            x = re.sub(
                r"<dc:description>.*?</dc:description>",
                "<dc:description></dc:description>",
                x,
                flags=re.S,
            )
            x = re.sub(r"<dc:description/>", "<dc:description></dc:description>", x)
            # lastModifiedBy -> the person
            if "<cp:lastModifiedBy" in x:
                x = re.sub(
                    r"<cp:lastModifiedBy\s*/>",
                    f"<cp:lastModifiedBy>{author}</cp:lastModifiedBy>",
                    x,
                )
                x = re.sub(
                    r"<cp:lastModifiedBy>.*?</cp:lastModifiedBy>",
                    f"<cp:lastModifiedBy>{author}</cp:lastModifiedBy>",
                    x,
                    flags=re.S,
                )
            x = re.sub(
                r"<cp:revision>.*?</cp:revision>",
                f"<cp:revision>{revision}</cp:revision>",
                x,
                flags=re.S,
            )
            x = re.sub(
                r"(<dcterms:created[^>]*>).*?(</dcterms:created>)",
                rf"\g<1>{ts(created)}\g<2>",
                x,
                flags=re.S,
            )
            x = re.sub(
                r"(<dcterms:modified[^>]*>).*?(</dcterms:modified>)",
                rf"\g<1>{ts(modified)}\g<2>",
                x,
                flags=re.S,
            )
            data = x.encode("utf-8")

        elif item.filename == "docProps/app.xml":
            x = data.decode("utf-8", "ignore")
            # Assert nothing about the authoring app (don't claim Word); drop Company.
            x = re.sub(
                r"<Application>.*?</Application>", "<Application></Application>", x, flags=re.S
            )
            x = re.sub(r"<Company\s*/>", "<Company></Company>", x)
            x = re.sub(r"<Company>.*?</Company>", "<Company></Company>", x, flags=re.S)
            data = x.encode("utf-8")

        zout.writestr(item, data)

    zin.close()
    zout.close()
    with open(out_path, "wb") as f:
        f.write(buf.getvalue())
    return out_path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("in_path")
    ap.add_argument("out_path")
    ap.add_argument("--author", default=config.LEGAL_NAME)
    a = ap.parse_args()
    finalize(a.in_path, a.out_path, author=a.author)
    print(f"finalized -> {a.out_path}")


if __name__ == "__main__":
    sys.exit(main())
